[tool.black]
line-length = 120
target-version = [
  "py38",
  "py39",
  "py310",
  "py311",  
  "py312", 
]
[tool.pyright]
include = [
    "tests, src"
]

[tool.bandit.assert_used]
skips = ['*_test.py', '*/test_*.py']

[tool.isort]
multi_line_output = 3
profile = "black"
